name: Tests

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby_version: [2.6.6, 2.7.3, 3.0.2]
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.ruby == 'debug' }}
    # Has to be top level to cache properly
    env:
      BUNDLE_JOBS: 3
      BUNDLE_PATH: "vendor/bundle"
    steps:
      - uses: actions/checkout@master
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby_version }}
          bundler-cache: true
      - name: Test with Rake
        run: bin/rails test